/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import java.util.ArrayList;

/**
 *
 * @author valen
 */
public class VistaCalculadora extends javax.swing.JFrame {
    
    /**
     * Creates new form VistaCalculadora2
     */
    public VistaCalculadora() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoTexto = new javax.swing.JTextField();
        borrar = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        division = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        negativo = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        potencia = new javax.swing.JButton();
        parentesisIzq = new javax.swing.JButton();
        parentesisDer = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        suma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(153, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        campoTexto.setEditable(false);
        campoTexto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        borrar.setBackground(new java.awt.Color(243, 166, 53));
        borrar.setForeground(new java.awt.Color(255, 255, 255));
        borrar.setText("⌫");
        borrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(243, 166, 53));
        clear.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("C");
        clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(72, 161, 241));
        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("7");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(72, 161, 241));
        jButton8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("8");
        jButton8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(72, 161, 241));
        jButton9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("9");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        division.setBackground(new java.awt.Color(243, 166, 53));
        division.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        division.setForeground(new java.awt.Color(255, 255, 255));
        division.setText("/");
        division.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(72, 161, 241));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("4");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(72, 161, 241));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton5.setForeground(java.awt.Color.white);
        jButton5.setText("5");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(72, 161, 241));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton6.setForeground(java.awt.Color.white);
        jButton6.setText("6");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        multiplicacion.setBackground(new java.awt.Color(243, 166, 53));
        multiplicacion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        multiplicacion.setForeground(new java.awt.Color(255, 255, 255));
        multiplicacion.setText("*");
        multiplicacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionActionPerformed(evt);
            }
        });

        resta.setBackground(new java.awt.Color(243, 166, 53));
        resta.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        resta.setForeground(new java.awt.Color(255, 255, 255));
        resta.setText("-");
        resta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(72, 161, 241));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("2");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(72, 161, 241));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("1");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(72, 161, 241));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("3");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        negativo.setBackground(new java.awt.Color(72, 161, 241));
        negativo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        negativo.setForeground(new java.awt.Color(255, 255, 255));
        negativo.setText("+/-");
        negativo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        negativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negativoActionPerformed(evt);
            }
        });

        jButton0.setBackground(new java.awt.Color(72, 161, 241));
        jButton0.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton0.setForeground(new java.awt.Color(255, 255, 255));
        jButton0.setText("0");
        jButton0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        punto.setBackground(new java.awt.Color(72, 161, 241));
        punto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        punto.setForeground(new java.awt.Color(255, 255, 255));
        punto.setText(".");
        punto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        potencia.setBackground(new java.awt.Color(243, 166, 53));
        potencia.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        potencia.setForeground(new java.awt.Color(255, 255, 255));
        potencia.setText("^");
        potencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaActionPerformed(evt);
            }
        });

        parentesisIzq.setBackground(new java.awt.Color(41, 206, 88));
        parentesisIzq.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        parentesisIzq.setForeground(new java.awt.Color(255, 255, 255));
        parentesisIzq.setText("(");
        parentesisIzq.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        parentesisIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesisIzqActionPerformed(evt);
            }
        });

        parentesisDer.setBackground(new java.awt.Color(41, 206, 88));
        parentesisDer.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        parentesisDer.setForeground(new java.awt.Color(255, 255, 255));
        parentesisDer.setText(")");
        parentesisDer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        parentesisDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesisDerActionPerformed(evt);
            }
        });

        igual.setBackground(new java.awt.Color(41, 206, 88));
        igual.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        igual.setForeground(new java.awt.Color(255, 255, 255));
        igual.setText("=");
        igual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        suma.setBackground(new java.awt.Color(243, 166, 53));
        suma.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        suma.setForeground(new java.awt.Color(255, 255, 255));
        suma.setText("+");
        suma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoTexto)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(parentesisIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(parentesisDer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(negativo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(campoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(potencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(negativo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parentesisDer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parentesisIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Elimina el último carácter del campo de texto.
     * 
     * Si el campo de texto no está vacío, se elimina el último carácter de la cadena
     * actual. Si está vacío, no hace nada.
     * Si antes del número hay un indicador de negativo, borra tambien el indicador
     * 
     * @param evt El evento que dispara la acción.
     */
    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        String cadena = campoTexto.getText();
        if (!cadena.isEmpty()) {
        StringBuilder sb = new StringBuilder(cadena);
        sb.deleteCharAt(sb.length() - 1);
        if (!sb.isEmpty() && sb.charAt(sb.length() - 1)=='?') // Si se borra el número que va despues del indicador de negativo, borra tambien el negativo
            sb.deleteCharAt(sb.length() - 1);
        campoTexto.setText(sb.toString());
        }
    }//GEN-LAST:event_borrarActionPerformed
    /**
     * Limpia todo el contenido del campo de texto, dejando la calculadora en un estado inicial.
     * 
     * Este método se utiliza para reiniciar el campo de entrada de la calculadora. Al ser llamado, borra 
     * todo el contenido del campo de texto, lo que permite al usuario comenzar una nueva operación sin 
     * necesidad de eliminar cada carácter de forma manual.
     * 
     * Uso típico:
     * - Este método es comúnmente utilizado cuando se presiona el botón "C" (clear) en una calculadora, 
     *   que borra cualquier expresión o número que haya sido ingresado.
     * @param evt El evento que dispara la acción.
     */
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        campoTexto.setText("");
    }//GEN-LAST:event_clearActionPerformed
    
    /**
     * Añade el número 7 al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"7");
    }//GEN-LAST:event_jButton7ActionPerformed
    
    /**
     * Añade el número 8 al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"8");
    }//GEN-LAST:event_jButton8ActionPerformed
    
    /**
     * Añade el número 9 al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"9");
    }//GEN-LAST:event_jButton9ActionPerformed
    
    /**
     * Añade el operador de división al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"/");
    }//GEN-LAST:event_divisionActionPerformed
    /**
     * Añade el número 4 al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"4");
    }//GEN-LAST:event_jButton4ActionPerformed
    
    /**
     * Añade el número 5 al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"5");
    }//GEN-LAST:event_jButton5ActionPerformed
    
    /**
     * Añade el número 6 al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"6");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * Añade el operador de multiplicación al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"*");
    }//GEN-LAST:event_multiplicacionActionPerformed

    /**
     * Añade el operador de resta al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"-");
    }//GEN-LAST:event_restaActionPerformed

    /**
     * Añade el número 2 al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"2");
    }//GEN-LAST:event_jButton2ActionPerformed
 
    /**
     * Añade el número 1 al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"1");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Añade el número 3 al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"3");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * Añade el operador de negativo al campo de texto.
    * 
    * Este método evalúa si hay un número antes de agregar el signo de interrogación "?", 
    * que se utiliza como marcador para indicar que el número es negativo.
    * 
    * Detalles del proceso:
    * - Se recorre el campo de texto de derecha a izquierda para identificar si existe un número al final de la cadena.
    * - Si se encuentra un número, se añade un signo de interrogación "?" antes del número, lo que lo marcará como negativo.
    * - Si no hay un número al final, no se añade el signo de interrogación.
    * 
    * @param evt El evento que dispara la acción.
    */
    
    private void negativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativoActionPerformed
        // TODO add your handling code here:
        
        String texto=campoTexto.getText();
        String numero="";
        char c;
        int i=texto.length()-1;
        
        while(i>=0 && Character.isDigit(texto.charAt(i))){ 
            numero=texto.charAt(i)+numero;
            i--;
        }
        
        if(!numero.equals("")){
                String nuevoTexto = texto.substring(0, i+1)+"?"+numero;
                campoTexto.setText(nuevoTexto);
        }           
    }//GEN-LAST:event_negativoActionPerformed

    /**
     * Añade el número 0 al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"0");
    }//GEN-LAST:event_jButton0ActionPerformed

    /**
     * Añade un punto al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+".");
    }//GEN-LAST:event_puntoActionPerformed

    /**
     * Añade el operador de potencia al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"^");
    }//GEN-LAST:event_potenciaActionPerformed

    /**
     * Añade un paréntesis izquierdo al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void parentesisIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesisIzqActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"(");
    }//GEN-LAST:event_parentesisIzqActionPerformed

    /**
     * Añade un paréntesis derecho al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void parentesisDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesisDerActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+")");
    }//GEN-LAST:event_parentesisDerActionPerformed

    /**
    * Evalúa la expresión ingresada en el campo de texto y muestra el resultado.
    * 
    * Este método sigue los siguientes pasos:
    * 1. Verifica que la expresión ingresada sea válida utilizando {@link Calculadora#verificarExp(String)}.
    * 2. Convierte la expresión infija a una lista en notación postfija usando {@link Calculadora#conviertePostfijo(List)}.
    * 3. Evalúa la expresión postfija usando {@link Calculadora#evaluaPostfijo(List)}.
    * 
    * Detalles del proceso:
    * - Se convierte la cadena de la expresión en un {@link ArrayList} de tipo String, separando números y operadores. 
    *   Esto prepara la expresión para pasarla de infija a postfija.
    * 
    * Manejo de números negativos:
    * - Si se detecta un carácter de interrogación "?", se interpreta como un indicador de que el número es negativo.
    * - Se añade un signo negativo al número correspondiente antes de agregarlo a la lista.
    * - El signo "?" no se añade directamente a la lista, solo se utiliza como marcador para números negativos.
    * 
    * @param evt El evento que dispara la acción.
    */
    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
   // TODO add your handling code here:
        String expresion=campoTexto.getText();
        boolean negativo=false;
        
        if(Calculadora.verificarExp(expresion)){
            ArrayList<String> texto = new ArrayList<>();
            String numero="";
            for(int i=0;i<expresion.length();i++){
                char c=expresion.charAt(i);
                
                
                // Si el carácter es un dígito o un punto, es parte de un número
                if(Character.isDigit(c) || c=='.')
                    numero+=c;
                else if(c=='?'){ // Si hay un simbolo de interrogacion es un número negativo
                        negativo=true;
                        numero+='-'; // añado el simbolo negativo al número
                       // no añado el ? al array

                    }else{ // Cualquier otro operador
                    // Si el número no está vacío, agrégalo a la lista
                    if(!numero.equals("")){
                        texto.add(numero); // Agrega el número
                        numero=""; // Resetea la variable para el siguiente número
                    }
                    if(negativo)
                        negativo=false;
                    else
                        texto.add(c+""); // Agrega el operador o cualquier otro carácter
                }
            }
            if(!numero.equals(""))
                texto.add(numero); //En caso de que hubiera un número al final, lo añade
            double resultado=Calculadora.evaluaPostfijo(Calculadora.conviertePostfijo(texto));
            if(resultado==Double.NaN)
                campoTexto.setText("Syntax ERROR");
            else
                campoTexto.setText(resultado+"");
            
        } else
            campoTexto.setText("Syntax ERROR");
        
    }//GEN-LAST:event_igualActionPerformed

    /**
     * Añade el operador de suma al campo de texto.
     * 
     * @param evt El evento que dispara la acción.
     */
    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        // TODO add your handling code here:
        String texto=campoTexto.getText();
        campoTexto.setText(texto+"+");
    }//GEN-LAST:event_sumaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try { 
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) { 
            if ("Nimbus".equals(info.getName())) { 
                javax.swing.UIManager.setLookAndFeel(info.getClassName()); 
                break; 
            } 
        } 
    } catch (Exception ex) { 
        java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 
    }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JTextField campoTexto;
    private javax.swing.JButton clear;
    private javax.swing.JButton division;
    private javax.swing.JButton igual;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JButton negativo;
    private javax.swing.JButton parentesisDer;
    private javax.swing.JButton parentesisIzq;
    private javax.swing.JButton potencia;
    private javax.swing.JButton punto;
    private javax.swing.JButton resta;
    private javax.swing.JButton suma;
    // End of variables declaration//GEN-END:variables
}
